apiVersion: batch/v1
kind: Job
metadata:
  name: permission-test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: permission-test
        image: ghcr.io/arkaniad/permission-test:main
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Chicago
  backoffLimit: 4

