#!/usr/bin/env bash

echo "current - $(whoami) - $UID"

ls -al /usr/share/zoneinfo
ls -al /etc/localtime
ls -al /etc/timezone

if [[ ! -z "$TZ" ]]; then
  if [[ -f /usr/share/zoneinfo/$TZ ]]; then
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
    echo "$TZ" > /etc/timezone
  else
    echo "WARNING: $TZ is not a valid timezone."
  fi
fi

echo "done"
