#!/usr/bin/env bash
set -euo pipefail

echo "current - $(whoami) - $UID"

echo "perms: /usr/share/zoneinfo"
ls -al /usr/share/zoneinfo

echo "perms: /etc"
ls -al /etc

echo "perms: /etc/localtime"
ls -al /etc/localtime

echo "perms: /etc/timezone"

ls -al /etc/timezone

if [[ ! -z "$TZ" ]]; then
  if [[ -f /usr/share/zoneinfo/$TZ ]]; then
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
    echo "$TZ" > /etc/timezone
  else
    echo "WARNING: $TZ is not a valid timezone."
  fi
fi

echo "done"
